http:
    middlewares:
        security-headers:
            headers:
                browserXssFilter: true
                contentTypeNosniff: true
                frameDeny: true
                sslRedirect: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 31536000
                customFrameOptionsValue: "SAMEORIGIN"
        https-redirect:
            redirectScheme:
                scheme: https
        authentication:
            forwardAuth:
                trustForwardHeader: true
                tls:
                    insecureSkipVerify: true
                address: 'https://start.domain.lo/'
