version: '3.7'
services:
    reverse_proxy:
        image: traefik:2.2
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
            - ./custom:/etc/traefik/custom:ro
            - certs:/letsencrypt
        networks:
            - traefik_network

volumes:
    certs:

networks:
    traefik_network:
        external: true
