entryPoints:
    web:
        address: :80
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
    websecure:
        address: :443
        http:
            tls:
                certResolver: myresolver
            middlewares:
                - SecHeaders@file

accessLog: { }
http:
    middlewares:
        secHeaders:
            headers:
                browserXssFilter: true
                contentTypeNosniff: true
                frameDeny: true
                sslRedirect: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 31536000
                customFrameOptionsValue: "SAMEORIGIN"
        https-redirect:
            redirectScheme:
                scheme: https

providers:
    docker:
        exposedByDefault: false
    file:
        directory: /etc/traefik/custom/
        watch: true

certificatesResolvers:
    myresolver:
        acme:
            email: "adrien@chinour.fr"
            storage: "/letsencrypt/acme.json"
            tlsChallenge: { }

api:
    dashboard: true
    insecure: true
