version: '3.7'
services:

    nextcloud:
        image: ghcr.io/linuxserver/nextcloud
        container_name: nextcloud
        restart: unless-stopped
        environment:
            - PUID=1300
            - PGID=1300
            - TZ=Europe/Paris
        volumes:
            - /home/nextcloud/config:/config
            - /cloud:/data
        networks:
            - traefik_network
            - lan
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_network"
            - "traefik.http.routers.nextcloud.entrypoints=websecure"
            - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOST}`)"
            - "traefik.http.routers.nextcloud.tls=true"
            - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
            - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav"
            - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
            - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
            - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
            - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"

    mariadb:
        image: ghcr.io/linuxserver/mariadb
        container_name: mariadb
        restart: unless-stopped
        networks:
            - lan
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=Europe/Paris
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USERNAME}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - db:/config
        ports:
            - 3306:3306

volumes:
    db:

networks:
    traefik_network:
        external: true
    lan:
