version: '3.7'
services:
    database:
        image: jsurf/rpi-mariadb:latest
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: unless-stopped
        environment:
            PUID: '1200'
            PGID: '1200'
            TZ: 'Europe/Paris'
            MYQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - lan
        volumes:
            - db:/var/lib/mysql

    nextcloud:
        depends_on:
            - database
        image: nextcloud:18
        restart: unless-stopped
        environment:
            PUID: '1200'
            PGID: '1200'
            TZ: 'Europe/Paris'
            MYSQL_HOST: 'database'
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_HOST}
        networks:
            - lan
            - traefik_network
        volumes:
            - html:/var/www/html
            - /cloud:/var/www/html/data
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_network"
            - "traefik.http.routers.nextcloud.entrypoints=websecure"
            - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOST}`)"
            - "traefik.http.routers.nextcloud.tls=true"
            - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
            - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav"
            - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
            - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
            - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"

volumes:
    db:
    html:

networks:
    traefik_network:
        external: true
    lan:
