version: '3.7'
services:
    database:
        image: jsurf/rpi-mariadb:latest
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: unless-stopped
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: 'nextcloud'
            MYSQL_USER: 'nextcloud_user'
            MYSQL_PASSWORD: 'not a strong password'
        networks:
            - lan
        volumes:
            - db:/var/lib/mysql

    nextcloud:
        depends_on:
            - database
        image: nextcloud:18
        restart: unless-stopped
        environment:
            MYSQL_HOST: 'database'
            MYSQL_DATABASE: 'nextcloud'
            MYSQL_USER: 'nextcloud_user'
            MYSQL_PASSWORD: 'not a strong password'
            NEXTCLOUD_ADMIN_PASSWORD: 'not a strong password'
            NEXTCLOUD_ADMIN_USER: 'adrien'
            NEXTCLOUD_TRUSTED_DOMAINS: 'nextcloud.pi.chinour.fr'
        networks:
            - lan
            - traefik_network
        volumes:
            - html:/var/www/html
        labels:
            traefik.enable: 'true'
            traefik.docker.network: 'traefik_network'
            traefik.http.routers.nextcloud.entrypoints: 'websecure'
            traefik.http.routers.nextcloud.rule: 'Host(`nextcloud.pi.chinour.fr`)'
            traefik.http.middlewares.nc-header.headers.referrerPolicy: 'no-referrer'
            traefik.http.middlewares.nc-header.headers.stsSeconds: '31536000'
            traefik.http.middlewares.nc-header.headers.forceSTSHeader: 'true'
            traefik.http.middlewares.nc-header.headers.stsPreload: 'true'
            traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains: 'true'
            traefik.http.middlewares.nc-header.headers.browserXssFilter: 'true'
            traefik.http.middlewares.nc-header.headers.customRequestHeaders.X-Forwarded-Proto: 'https'
            traefik.http.routers.nextcloud-secure.middlewares: 'nextcloud-rep,nc-header'

volumes:
    db:
    html:

networks:
    traefik_network:
        external: true
    lan:
