[providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false

[entryPoints]
    [entryPoints.web]
        address = ":80"
        [entryPoints.web.http]
            [entryPoints.web.http.redirections]
                [entryPoints.web.http.redirections.entryPoint]
                    to = "websecure"
                    scheme = "https"
                    permanent = true
    [entryPoints.websecure]
        address = ":443"
            [entryPoints.websecure.http.tls]
                certResolver = "myresolver"

[certificatesResolvers]
    [certificatesResolvers.myresolver]
        [certificatesResolvers.myresolver.acme]
            email = "adrien@chinour.fr"
            storage = "acme.json"
            [certificatesResolvers.myresolver.acme.tlsChallenge]
[api]
    dashboard = true
    insecure = true
